re_type_mapping = {
    "Đất": "Đất",
    "Bán đất": "Đất",
    "Nhà riêng": "Nhà riêng",
    "Văn phòng": "Văn phòng",
    "Bán condotel": "Bất động sản khác",
    "Bán nhà riêng": "Nhà riêng",
    "Nhà mặt phố": "Nhà mặt phố",
    "Kho, nhà xưởng": "Kho, nhà xưởng",
    "Căn hộ chung cư": "Căn hộ chung cư",
    "Bán nhà mặt phố": "Nhà mặt phố",
    "Bán kho, nhà xưởng": "Kho, nhà xưởng",
    "Bán căn hộ chung cư": "Căn hộ chung cư",
    "Nhà trọ, phòng trọ": "Nhà trọ, phòng trọ",
    "Mặt bằng, cửa hàng": "Mặt bằng, cửa hàng",
    "Bán đất nền dự án": "Đất nền dự án",
    "Bán nhà biệt thự, liền kề": "Biệt thự",
    "Bán loại bất động sản khác": "Bất động sản khác",
    "Biệt thự": "Biệt thự",
    "Bán trang trại, khu nghỉ dưỡng": "Trang trại, khu nghỉ dưỡng",
    "Bất động sản khác": "Bất động sản khác",
    "Shop-house": "Bất động sản khác",
    "Đất nền dự án": "Đất nền dự án",
    "Đất nền - Đất ở - Đất thổ cư": "Đất",
    "Đất dự án": "Đất nền dự án",
    "Cho thuê kho, nhà xưởng, đất": "Kho, nhà xưởng",
    "Nhà phố": "Nhà mặt phố",
    "Cho thuê nhà mặt phố": "Nhà mặt phố",
    "Nhà Kho - Xưởng": "Kho, nhà xưởng",
    "Bán nhà phố": "Nhà mặt phố",
    "Bán nhà hàng - Khách sạn": "Nhà hàng - Khách sạn",
    "Đất nông, lâm nghiệp": "Đất nông, lâm nghiệp",
    "Mặt bằng": "Mặt bằng, cửa hàng",
    "Nhà hàng - Khách sạn": "Nhà hàng - Khách sạn",
    "Phòng trọ": "Nhà trọ, phòng trọ",
    "Cho thuê cửa hàng, kiot": "Mặt bằng, cửa hàng",
    "Bán văn phòng": "Văn phòng",
    "Cho thuê căn hộ chung cư": "Căn hộ chung cư",
    "Cho thuê nhà riêng": "Nhà riêng",
    "Cho thuê văn phòng": "Văn phòng",
    "Bán phòng trọ": "Nhà trọ, phòng trọ",
    "Cho thuê phòng trọ, nhà trọ": "Nhà trọ, phòng trọ",
    "Pent-house": "Bất động sản khác",
    "Cho thuê loại bất động sản khác": "Bất động sản khác",
    "Office-tel": "Bất động sản khác",
    "Khu nghỉ dưỡng, trang trại": "Trang trại, khu nghỉ dưỡng",
    "Cho thuê cửa hàng, ki ốt": "Mặt bằng, cửa hàng"
}