import scrapy

# class CrawlerItem(scrapy.Item):
#     # define the fields for your item here like:
    
#     User = scrapy.Field()
#     Comment = scrapy.Field()
#     Time = scrapy.Field()
class Nhadat247_Ban_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Facade = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()
    Contact_city = scrapy.Field()
    Contact_type = scrapy.Field()

class Nhadat247_Thue_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Facade = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()
    Contact_city = scrapy.Field()
    Contact_type = scrapy.Field()

class Nhadatban24h_Ban_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Facade = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()

class Nhadatban24h_Thue_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Facade = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()

class Alomuabannhadat_Ban_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()

class Alomuabannhadat_Thue_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()

class Alomuabannhadat_Dat_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()

class Cafeland_Ban_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()

class Cafeland_Thue_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
    Contact_email = scrapy.Field()
    Contact_address = scrapy.Field()

class Nhadatvui_Ban_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()
class Nhadatvui_Thue_Item(scrapy.Item):
    URL = scrapy.Field()
    Title = scrapy.Field()
    Created_date = scrapy.Field()
    Crawled_date = scrapy.Field()
    Post_id = scrapy.Field()
    Price = scrapy.Field()
    Acreage = scrapy.Field()
    Location = scrapy.Field()
    RE_Type = scrapy.Field()
    Legal = scrapy.Field()
    Street_size = scrapy.Field()
    Vertical_length = scrapy.Field()
    Horizontal_length = scrapy.Field()
    Direction = scrapy.Field()
    Num_rooms = scrapy.Field()
    Num_toilets = scrapy.Field()
    Num_floors = scrapy.Field()
    Description = scrapy.Field()
    Contact_name = scrapy.Field()
    Contact_phone = scrapy.Field()