version: '3'

services:
  minio:
    image: minio/minio
    container_name: coursehub-minio
    hostname: coursehub-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: tranvietcuong
      MINIO_ROOT_PASSWORD: tranvietcuong
    command: server --console-address ":9001" /data
    networks:
      - milvus-network
networks:
  milvus-network:
    external: true
